package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.s3Storage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            s3Storage {
                id = "PROJECT_EXT_11"
                awsEnvironment = default {
                    awsRegionName = "eu-west-1"
                }
                credentials = accessKeys()
                accessKeyID = "AKIA5JH2VERVI62P5XDY"
                accessKey = "credentialsJSON:23f35f69-163d-45a1-bc3f-23e91c0363ff"
                bucketName = "tc-dkrupkina-acceleration"
            }
        }
    }
}
